### PR TITLE
Enable mermaid diagrams

### PR DESCRIPTION
**Pull request by btat**

### CODE REVIEW

**Comment by jhkrug** [comment]
ok, but, I added Kroki a while back to do Mermaid for KW. Was it not enough for your requirement?

**Comment by btat** [comment]
Kroki wasn't working for my case and would produce conversion errors.

antora-diagram

The page from the screenshot is [this K3s page](https://github.com/rancher/k3s-product-docs/blob/main/versions/latest/modules/en/pages/cli/certificate.adoc?plain=1), which has 3 mermaid diagrams. The syntax used on that page seems to match what's listed on the [Kroki docs](https://github.com/asciidoctor/asciidoctor-kroki?) and I also tried including the optional attributes the docs mention to no avail.

Even the simple example from the Kroki docs give the same error.

```
[mermaid,abcd-flowchart,svg]
....
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
....
```

**Comment by jhkrug** [comment]
Interesting, I saw that error a while back for my couple of KW diagrams. It got fixed somehow, but my memory is failing me at the moment.

**Comment by jhkrug** [comment]
Hi @btat . Over the weekend the memory was finally dragged back to the foreground. While out cycling. I got this error when I had the mermaid diagram in place but had not created/moved the images into place in the source tree in modules/en/images or whatever.

If I move the images directory out of the way but keep the mermaid diagram in place, I get the error again. Along with a load of missing image errors, of course. Reinstate the image directory and all is well again. 

If the image directory is not present in the source, a _images directory doesn't get created in the build directory, so there is nowhere to put what mermaid produces. Maybe. A make clean, prior to build, or npx antora generate --clean, is also necessary to generate the error. If there is a _image directory hanging around from previous builds then all is well.

Perhaps, the other mermaid renderer manages the potential situation better. Or, maybe, there are many paths to getting that error.

**Pull request merged**
